import React, { useEffect, useMemo, useRef, useState } from "react";
import { LazyMotion, MotionConfig, domAnimation, useReducedMotion } from "motion/react";
import * as m from "motion/react-m";
import { widgetRegistry } from "./widget-registry.jsx";

const staticToneClasses = Object.freeze({
 neutral: "ic-card ic-tone-neutral border border-black/10 dark:border-white/15 bg-black/[0.025] dark:bg-white/[0.035]",
 note: "ic-card ic-tone-note border border-blue-700/20 dark:border-blue-300/25 bg-blue-500/[0.055]",
 warning: "ic-card ic-tone-warning border border-amber-700/25 dark:border-amber-300/25 bg-amber-500/[0.07]",
 good: "ic-card ic-tone-good border border-emerald-700/20 dark:border-emerald-300/25 bg-emerald-500/[0.055]",
});
const buttonClass = "ic-button min-h-10 rounded-lg border border-black/10 px-3 py-2 text-sm dark:border-white/15";

const feedbackOptions = Object.freeze([
 ["unclear-explanation","讲解不够清楚"],["missing-example","缺少例子/反例"],["incorrect-content","内容疑似不正确"],
 ["interaction-friction","交互不顺/有 bug"],["math-or-notation","公式/符号表达问题"],["pacing-or-depth","节奏或深度不合适"],
 ["source-question","出处/证据有疑问"],["worked-well","这段解释/交互特别有效"],["figure-helpful","教学图特别有帮助"],
 ["figure-confusing-or-missing","图示不清楚 / 缺少图示"],["animation-content-mismatch","动画对象/动作和所讲内容不贴切"],
 ["animation-too-fast","动画节奏太快 / 难以跟上"],["animation-misleading","动画可能造成错误理解"],["animation-helpful","动画特别帮助理解原理"],
]);

function flattenText(value){
 if(value==null) return "";
 if(typeof value==="string" || typeof value==="number" || typeof value==="boolean") return String(value);
 if(Array.isArray(value)) return value.map(flattenText).join(" ");
 if(typeof value==="object") return Object.entries(value).filter(([k])=>!['answer','solution'].includes(k)).map(([,v])=>flattenText(v)).join(" ");
 return "";
}

function downloadFeedback(course, observations){
 if(!observations.length) return false;
 const payload={schema:"interactive-classroom-session-feedback",explicitUserExport:true,exportedAt:new Date().toISOString(),course:{title:course?.meta?.title||"互动学习",courseId:course?.meta?.id||null,schemaProfile:"stage-scene",disciplinePack:course?.meta?.disciplinePack||null,secondaryPacks:course?.meta?.secondaryPacks||[]},policy:{telemetry:"explicit-user-entered-only",automaticSkillChange:false},observations};
 const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a");
 const slug=String(course?.meta?.disciplinePack||"course").replace(/[^a-z0-9-]+/gi,"-"); a.href=url; a.download=`interactive-classroom-feedback-${slug}.json`; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); return true;
}

function Modal({ title, onClose, children, label=title }){
 const boxRef=useRef(null); const previous=useRef(null);
 useEffect(()=>{ previous.current=document.activeElement; const box=boxRef.current; const focusables=()=>[...box.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled); focusables()[0]?.focus();
  const onKey=e=>{ if(e.key==='Escape'){e.preventDefault();onClose();return;} if(e.key==='Tab'){const xs=focusables();if(!xs.length)return;const first=xs[0],last=xs[xs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
  document.addEventListener('keydown',onKey); return()=>{document.removeEventListener('keydown',onKey); previous.current?.focus?.();};
 },[onClose]);
 return <div role="presentation" className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div ref={boxRef} role="dialog" aria-modal="true" aria-label={label} className="max-h-[88vh] w-full max-w-3xl overflow-auto rounded-2xl bg-[var(--ic-paper)] p-5 shadow-2xl"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><button type="button" onClick={onClose} className={buttonClass}>关闭</button></div>{children}</div></div>;
}

function FeedbackDialog({ course, scene, observations, setObservations, onClose }){
 const [types,setTypes]=useState([]),[rating,setRating]=useState(null),[note,setNote]=useState(""),[scopeHint,setScopeHint]=useState("unknown"),[status,setStatus]=useState("");
 const toggleType=type=>setTypes(xs=>xs.includes(type)?xs.filter(x=>x!==type):[...xs,type]);
 const addObservation=()=>{const clean=note.trim();if(!types.length&&rating==null&&!clean){setStatus("请至少选择一个反馈类型、评分或填写说明。");return;} setObservations(xs=>[...xs,{sceneId:scene?.id||null,sceneTitle:scene?.title||"",objectiveIds:scene?.objectiveIds||[],types:[...new Set(types)],rating,note:clean,scopeHint,recordedAt:new Date().toISOString()}]);setTypes([]);setRating(null);setNote("");setScopeHint("unknown");setStatus("已加入本次学习反馈。");};
 const exportNow=()=>setStatus(downloadFeedback(course,observations)?"已导出学习反馈。":"请先加入至少一条反馈。");
 return <Modal title="学习反馈" onClose={onClose}><p className="mt-1 text-sm opacity-65">当前：{scene?.title||"学习页"}</p><p className="mt-4 text-sm/6 opacity-75">只记录你主动填写的学习体验，并导出到本地 JSON。不会联网、不会自动修改 Skill。</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{feedbackOptions.map(([value,label])=><label key={value} className="flex gap-2 rounded-lg border border-black/10 p-3 text-sm dark:border-white/15"><input type="checkbox" checked={types.includes(value)} onChange={()=>toggleType(value)}/><span>{label}</span></label>)}</div><fieldset className="mt-5"><legend className="text-sm font-semibold">这页帮助你理解的程度</legend><div className="mt-2 flex flex-wrap gap-2">{[1,2,3,4,5].map(n=><label key={n} className="flex min-h-10 items-center gap-2 rounded-full border border-black/10 px-3 dark:border-white/15"><input type="radio" name="modern-feedback-rating" checked={rating===n} onChange={()=>setRating(n)}/>{n}</label>)}</div></fieldset><label className="mt-5 block text-sm font-semibold">补充说明<textarea value={note} onChange={e=>setNote(e.target.value.slice(0,5000))} className="mt-2 min-h-28 w-full rounded-lg border border-black/15 bg-transparent p-3 font-normal dark:border-white/20" placeholder="例如：哪个步骤仍然不清楚，或者哪个动画最帮助理解。"/></label><label className="mt-4 block text-sm font-semibold">这个反馈主要针对<select value={scopeHint} onChange={e=>setScopeHint(e.target.value)} className="mt-2 min-h-10 w-full rounded-lg border border-black/15 bg-[var(--ic-paper)] px-3 font-normal dark:border-white/20"><option value="unknown">暂不判断</option><option value="course">当前知识点</option><option value="pack">同类知识的学习方式</option><option value="core">整体学习体验</option></select></label><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={addObservation} className="min-h-11 rounded-lg bg-[var(--ic-accent)] px-4 font-semibold text-white">加入本次反馈</button><button type="button" onClick={exportNow} className={buttonClass}>导出学习反馈</button><button type="button" onClick={()=>{setObservations([]);setStatus("已清空本次主动反馈。");}} className={buttonClass}>清空</button></div><p role="status" className="mt-3 text-sm opacity-70">{status||`当前 ${observations.length} 条主动反馈。`}</p></Modal>;
}

const mathTags=new Set(["math","mrow","mi","mn","mo","mtext","mspace","mfrac","msqrt","mroot","msup","msub","msubsup","munder","mover","munderover","mtable","mtr","mtd","menclose","semantics","annotation"]);
function sanitizeMathML(raw){if(typeof raw!=="string"||!raw.trim())return"";const doc=new DOMParser().parseFromString(raw,"application/xml");if(doc.querySelector("parsererror"))return"";const root=doc.documentElement;if(root.localName!=="math")return"";for(const el of[root,...root.querySelectorAll("*")]){if(!mathTags.has(el.localName))return"";for(const attr of[...el.attributes]){const n=attr.name.toLowerCase();if(n.startsWith("on")||["href","xlink:href","src","style"].includes(n))el.removeAttribute(attr.name);}}return new XMLSerializer().serializeToString(root);}
function MathML({value}){const safe=useMemo(()=>sanitizeMathML(value?.mathml||value),[value]);const fallback=value?.tex||value?.expression||value?.text||value?.spoken||((typeof value==="string"||typeof value==="number")?String(value):"数学表达式");if(!safe)return <code>{fallback}</code>;return <span className="ic-math" dangerouslySetInnerHTML={{__html:safe}}/>;}
 function RenderRich({value}){if(value==null)return null;if(typeof value==="string"||typeof value==="number")return <>{String(value)}</>;if(Array.isArray(value))return <>{value.map((x,i)=><React.Fragment key={i}><RenderRich value={x}/>{i<value.length-1&&typeof x==='string'?" ":null}</React.Fragment>)}</>;if(typeof value==="object"){if(value.mathml)return <MathML value={value}/>;if(value.formula)return <MathML value={value.formula}/>;if(value.text!=null)return <RenderRich value={value.text}/>;if(value.body!=null)return <RenderRich value={value.body}/>;if(value.label!=null)return <RenderRich value={value.label}/>;if(value.prompt!=null)return <RenderRich value={value.prompt}/>;}return null;}

class WidgetErrorBoundary extends React.Component{constructor(props){super(props);this.state={failed:false};}static getDerivedStateFromError(){return{failed:true};}componentDidCatch(error){console.error("Interactive widget failed",error);}render(){if(this.state.failed)return <div role="status" className={`${staticToneClasses.warning} rounded-xl p-4`}><strong>交互组件暂时不可用</strong><p className="mt-2 text-sm opacity-80">知识讲解仍可继续阅读。请重新加载页面或改用本节的非交互说明。</p></div>;return this.props.children;}}

function ListBlock({id,title,items,tone="neutral"}){if(!items?.length)return null;return <section id={id} className={`${staticToneClasses[tone]} rounded-xl p-4`}><h4 className="font-semibold">{title}</h4><ul className="mt-2 list-disc space-y-2 pl-5 text-base/7">{items.map((x,i)=><li key={i}><RenderRich value={x}/></li>)}</ul></section>;}

function SemanticBlock({block,index}){
 const kind=String(block?.kind||block?.type||"knowledge").toLowerCase(); const label=kind.replace(/-/g," "); const steps=block?.steps||[]; const hints=block?.hints||block?.progressiveHints||[];
 return <article id={block?.id||`semantic-${index}`} className={`${kind==="proof"?staticToneClasses.neutral:staticToneClasses.note} rounded-xl p-4`}><div className="text-xs font-semibold uppercase tracking-[.12em] opacity-60">{label}</div>{block?.title&&<h4 className="mt-1 font-semibold">{block.title}</h4>}{block?.of&&<p className="mt-2 text-sm opacity-70"><strong>证明对象：</strong><RenderRich value={block.of}/></p>}{block?.statement&&<div className="mt-3 text-base/8"><RenderRich value={block.statement}/></div>}{block?.formula&&<div className="mt-3"><MathML value={block.formula}/></div>}{block?.body&&<div className="mt-3 text-base/8"><RenderRich value={block.body}/></div>}{block?.text&&<div className="mt-3 text-base/8"><RenderRich value={block.text}/></div>}{block?.prompt&&<div className="mt-3 text-base/8"><strong>问题：</strong><RenderRich value={block.prompt}/></div>}{block?.strategy&&<div className="mt-3 text-base/8"><strong>策略：</strong><RenderRich value={block.strategy}/></div>}{block?.proofSketch&&<div className="mt-3 text-base/8"><strong>证明思路：</strong><RenderRich value={block.proofSketch}/></div>}{steps.length?<ol className="mt-3 list-decimal space-y-2 pl-5 text-base/7">{steps.map((s,i)=><li key={s.id||i}><RenderRich value={s.text??s.body??s}/>{s.formula&&<div className="mt-1"><MathML value={s.formula}/></div>}</li>)}</ol>:null}{block?.result&&<div className="mt-3 text-base/8"><strong>结果：</strong><RenderRich value={block.result}/></div>}{block?.conclusion&&<div className="mt-3 text-base/8"><strong>结论：</strong><RenderRich value={block.conclusion}/></div>}{hints.length?<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">渐进提示</summary><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">{hints.map((h,i)=><li key={i}><RenderRich value={h}/></li>)}</ol></details>:null}{block?.solution&&<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">查看解答</summary><div className="mt-2 text-sm/7"><RenderRich value={block.solution}/></div></details>}{block?.references?.length?<p className="mt-3 text-xs opacity-60">语义引用：{block.references.map((r,i)=><code key={i} className="ml-1">{typeof r==='string'?r:r.id||r.targetId}</code>)}</p>:null}</article>;
}

 function MotionComponentsFigure({figure}){
  const oblique=String(figure?.variant||'').toLowerCase().includes('oblique');
  const points=oblique?'72,222 132,170 205,130 286,102 370,88 452,96 528,126 584,168':'72,222 145,206 220,180 298,146 380,106 464,62 548,18';
  const ball=oblique?{x:132,y:170}:{x:220,y:180};
  return <svg viewBox="0 0 640 270" className="ic-figure-svg" role="img" aria-label={figure?.caption||figure?.title||'运动分量教学图'}>
   <line x1="54" y1="230" x2="600" y2="230" stroke="currentColor" opacity=".35"/><line x1="54" y1="230" x2="54" y2="24" stroke="currentColor" opacity=".35"/>
   <polyline points={points} fill="none" stroke="var(--ic-accent)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" opacity=".72"/>
   <circle cx={ball.x} cy={ball.y} r="9" fill="var(--ic-accent)"/><line x1={ball.x} y1={ball.y} x2={ball.x+78} y2={ball.y} stroke="var(--ic-good)" strokeWidth="4"/><line x1={ball.x} y1={ball.y} x2={ball.x} y2={ball.y+46} stroke="var(--ic-warn)" strokeWidth="4"/>
   <text x="600" y="252" textAnchor="end" fontSize="13">x / 水平位置</text><text x="46" y="20" textAnchor="end" fontSize="13">y / 高度</text>
   <text x={ball.x+82} y={ball.y-8} fontSize="13" fill="var(--ic-good)">水平分量</text><text x={ball.x+8} y={ball.y+62} fontSize="13" fill="var(--ic-warn)">竖直分量</text><text x="575" y="42" textAnchor="end" fontSize="13" fill="var(--ic-accent)">轨迹</text>
  </svg>;
 }

 function GenericFigureVisual({figure}){
  const nodes=figure?.nodes||[],edges=figure?.edges||[],by=Object.fromEntries(nodes.map(n=>[n.id,n]));
  return nodes.length?<svg viewBox="0 0 640 300" className="ic-figure-svg" role="img" aria-label={figure?.caption||figure?.title||"教学图"}>
   {edges.map((e,i)=>{const a=by[e.from],b=by[e.to];if(!a||!b)return null;return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="currentColor" opacity=".35"/>})}
   {nodes.map(n=><g key={n.id}><rect x={Number(n.x)-70} y={Number(n.y)-22} width="140" height="44" rx="12" fill="var(--ic-paper)" stroke="currentColor"/><text x={n.x} y={Number(n.y)+5} textAnchor="middle" fontSize="13">{n.label}</text></g>)}
  </svg>:<div className="ic-figure-empty" role="img" aria-label={figure?.caption||figure?.title||"教学图"}>此教学图需要课程生成阶段提供可渲染的图形数据。</div>;
 }

 function PedagogicalFigure({figure,compact=false,exampleId}){
  const visual=figure?.template==='motion-components'?<MotionComponentsFigure figure={figure}/>:<GenericFigureVisual figure={figure}/>;
  return <figure className={`${staticToneClasses.neutral} ic-knowledge-figure rounded-xl p-4`} data-pedagogical-figure="true" data-figure-id={figure?.id||""} data-figure-kind={figure?.figureKind||"concept"} data-example-figure={exampleId||undefined}>
   <figcaption className="ic-figure-caption"><div><strong>{figure?.title||"教学图"}</strong>{figure?.learningPurpose&&<span className="ml-2 text-sm opacity-65">{figure.learningPurpose}</span>}</div><span className="ic-figure-badge">{figure?.figureKind||"concept"}</span></figcaption>
   <div className={`ic-figure-visual ${compact?"ic-figure-visual--compact":""}`}>{visual}</div>
   {figure?.caption&&<p className="mt-2 text-sm opacity-70">{figure.caption}</p>}
   {!!figure?.highlights?.length&&<ul className="ic-figure-highlights mt-3 text-xs opacity-75">{figure.highlights.map((item,index)=><li key={index}>{item}</li>)}</ul>}
  </figure>;
 }

 function knowledgeOutline(knowledge){if(!knowledge)return[];const out=[];const add=(id,label,ok)=>{if(ok)out.push({id,label});};add("k-summary","概要",knowledge.summary);add("k-prerequisites","先修连接",knowledge.prerequisites?.length);add("k-mental-model","心智模型",knowledge.mentalModel||knowledge.intuition);add("k-definition","准确表述",knowledge.definition||knowledge.definitionFormula);add("k-mechanism","机制 / 推理",knowledge.mechanism);(knowledge.sections||[]).forEach((s,i)=>add(`k-section-${i}`,s.title||`展开 ${i+1}`,true));add("k-semantic","教材语义块",knowledge.semanticBlocks?.length);add("k-figures","教学图",knowledge.pedagogicalFigures?.length);add("k-examples","例题 / 证据",knowledge.workedExamples?.length||knowledge.example||knowledge.evidence);add("k-comparison","对比理解",knowledge.comparison?.rows?.length);add("k-pitfalls","边界与误区",knowledge.boundaries?.length||knowledge.pitfalls?.length);add("k-check","自检",knowledge.checkYourself?.length);return out;}

// Formula-aware Knowledge renderer is defined below.

// The typed quiz renderer is defined below.
// The typed mastery summary is defined below.

function ExplainBackScene({content}){const [text,setText]=useState(""),[show,setShow]=useState(false);return <section className="ic-reading"><div className={`${staticToneClasses.note} rounded-xl p-4`}><h3 className="font-semibold">用自己的话解释</h3><p className="mt-2 text-base/8"><RenderRich value={content?.prompt}/></p><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-4 min-h-36 w-full rounded-lg border border-black/15 bg-transparent p-3 dark:border-white/20" placeholder="先不看提示，用自己的话解释机制、条件和边界。"/><button type="button" className={`${buttonClass} mt-3`} onClick={()=>setShow(v=>!v)}>{show?"隐藏检查点":"对照关键点"}</button>{show&&<div className="mt-3"><ListBlock title="应覆盖的关键思想" items={content?.requiredIdeas} tone="good"/><ListBlock title="常见缺口" items={content?.commonGaps} tone="warning"/></div>}<p className="mt-3 text-xs opacity-60">本地自我解释，不调用远程模型自动评分。</p></div></section>;}

function StructuredScene({scene}){const c=scene?.content||{};const keys=["prompt","question","task","scenario","brief","instructions","goal","reflectionPrompt","checkpoint","successCriteria","deliverables","constraints","roles","steps","questions","rubric"];return <section className="ic-reading space-y-4" data-modern-scene={scene?.type}>{keys.map(k=>c[k]!=null?<section key={k} className={`${staticToneClasses.neutral} rounded-xl p-4`}><h3 className="text-xs font-semibold uppercase tracking-[.12em] opacity-60">{k}</h3><div className="mt-2 text-base/8"><RenderRich value={c[k]}/></div></section>:null)}</section>;}

function WidgetSlot({scene,course}){const type=scene?.content?.widgetType;if(!type)return null;const Component=widgetRegistry[type];if(!Component)return <div className={`${staticToneClasses.warning} rounded-xl p-4 text-sm`} data-missing-widget={type}>生成阶段必须为 <code>{type}</code> 注册组件；正式交付不得保留此占位。</div>;return <div className="ic-widget-frame"><WidgetErrorBoundary><Component scene={scene} course={course}/></WidgetErrorBoundary></div>;}

function SceneBody({scene,course}){const knowledge=scene?.knowledge||scene?.content?.knowledge;const type=scene?.type;return <div className="space-y-8"><Knowledge knowledge={knowledge}/>{type==='orientation'&&scene?.content?.text?<section className="ic-reading text-base/8"><RenderRich value={scene.content.text}/></section>:null}{type==='quiz'?<QuizScene content={scene.content}/>:null}{type==='mastery'?<QuizScene content={scene.content} mastery/>:null}{type==='explain-back'?<ExplainBackScene content={scene.content}/>:null}{['discussion','pbl','reflection','checkpoint'].includes(type)?<StructuredScene scene={scene}/>:null}{type==='interactive'?<div className="ic-reading"><WidgetSlot scene={scene} course={course}/></div>:null}</div>;}

function collectCitationIds(value,out=new Set()){if(Array.isArray(value)){value.forEach(v=>collectCitationIds(v,out));return out;}if(value&&typeof value==='object'){if(Array.isArray(value.citations))for(const c of value.citations){const id=typeof c==='string'?c:c?.sourceId;if(id)out.add(id);}for(const [k,v] of Object.entries(value))if(k!=='citations')collectCitationIds(v,out);}return out;}
function CitationTrail({scene,sources}){const refs=[...collectCitationIds(scene)];if(!refs.length)return null;const sourceIndex=new Map((sources||[]).map((s,i)=>[s.id,i+1]));return <div className="ic-reading mt-8 border-t border-black/10 pt-4 text-sm opacity-75 dark:border-white/15"><strong>本页来源：</strong>{refs.map((id,i)=><span key={`${id}-${i}`} className="ml-2">[{sourceIndex.get(id)??"?"}] {id}</span>)}</div>;}

 function FormulaBlock({value,label="公式"}){if(value==null)return null;return <div className="ic-formula-block" data-formula-block="true"><span className="sr-only">{label}</span><MathML value={value}/></div>;}

 function WorkedStepView({step,index}){
  const structured=step&&typeof step==="object"; const body=structured?(step.text??step.body??step.explanation):step; const formula=structured?step.formula:null;
  return <li className="ic-worked-step"><div className="ic-worked-step__head"><span className="ic-worked-step__number">步骤 {index+1}</span><span><RenderRich value={body}/></span></div>{formula&&<FormulaBlock value={formula} label={`步骤 ${index+1} 的公式`}/>} {structured&&step.reason&&<p className="ic-worked-step__reason"><strong>理由：</strong><RenderRich value={step.reason}/></p>} {structured&&step.note&&<p className="ic-worked-step__note"><RenderRich value={step.note}/></p>}</li>;
 }

 function WorkedExample({example,index,figure}){
  const ex=typeof example==="string"?{text:example}:example||{}; const steps=Array.isArray(ex.steps)?ex.steps:[];
  return <article className={`${staticToneClasses.good} ic-worked-example rounded-xl p-4`} data-worked-example={ex.id||`example-${index+1}`}>
   <div className="ic-worked-example__head"><strong>{ex.title||`例 ${index+1}`}</strong>{ex.variantType&&<span className="ic-figure-badge">{ex.variantType}</span>}</div>
   {ex.prompt&&<p className="mt-2 text-base/8"><strong>题目：</strong><RenderRich value={ex.prompt}/></p>}
   {(ex.text??ex.body)&&<div className="mt-2 text-base/8"><RenderRich value={ex.text??ex.body}/></div>}
   {ex.formula&&<FormulaBlock value={ex.formula} label="例题公式"/>}
   {figure&&<PedagogicalFigure figure={figure} compact exampleId={ex.id||`example-${index+1}`}/>} 
   {steps.length?<ol className="ic-worked-steps mt-3">{steps.map((step,stepIndex)=><WorkedStepView key={step.id||stepIndex} step={step} index={stepIndex}/>)}</ol>:null}
   {ex.result&&<div className="ic-worked-result mt-3"><strong>结论：</strong><RenderRich value={ex.result}/></div>}
   {ex.resultFormula&&<FormulaBlock value={ex.resultFormula} label="例题结论公式"/>}
  </article>;
 }

 function ComparisonBlock({comparison}){if(!comparison?.headers?.length||!comparison?.rows?.length)return null;return <section id="k-comparison" className="ic-comparison-block space-y-2"><h4 className="text-sm font-semibold opacity-65">对比理解</h4><div className="overflow-x-auto"><table className="ic-comparison-table"><thead><tr>{comparison.headers.map((header,index)=><th key={index}><RenderRich value={header}/></th>)}</tr></thead><tbody>{comparison.rows.map((row,rowIndex)=><tr key={rowIndex}>{row.map((cell,cellIndex)=><td key={cellIndex}><RenderRich value={cell}/></td>)}</tr>)}</tbody></table></div></section>;}

 function Knowledge({knowledge}){
  if(!knowledge)return null;
  const mental=knowledge.mentalModel||knowledge.intuition;
  const examples=[...(knowledge.workedExamples||[])]; if(knowledge.example)examples.unshift(typeof knowledge.example==="string"?{title:"例子",text:knowledge.example}:knowledge.example);
  const figures=Array.isArray(knowledge.pedagogicalFigures)?knowledge.pedagogicalFigures:[];
  const figureById=Object.fromEntries(figures.filter((figure)=>figure?.id).map((figure)=>[figure.id,figure]));
  const inlineFigureIds=new Set(examples.map((example)=>example&&typeof example==="object"?example.figureRef:null).filter(Boolean));
  const standaloneFigures=figures.filter((figure)=>!inlineFigureIds.has(figure.id));
  return <article className="ic-reading space-y-7" data-knowledge-renderer="rich-parity">
   {knowledge.title&&<h3 className="text-xl font-semibold tracking-tight">{knowledge.title}</h3>}
   {knowledge.summary&&<section id="k-summary"><p className="text-base/8 opacity-85"><RenderRich value={knowledge.summary}/></p></section>}
   <ListBlock id="k-prerequisites" title="先修连接" items={knowledge.prerequisites}/>
   {mental&&<section id="k-mental-model" className="space-y-2"><h4 className="text-sm font-semibold opacity-65">心智模型</h4><div className="text-base/8"><RenderRich value={mental}/></div></section>}
   {knowledge.definition&&<section id="k-definition" className="space-y-2"><h4 className="text-sm font-semibold opacity-65">准确表述</h4><div className="text-base/8"><RenderRich value={knowledge.definition}/></div>{knowledge.definitionFormula&&<FormulaBlock value={knowledge.definitionFormula} label="定义公式"/>}</section>}
   {!knowledge.definition&&knowledge.definitionFormula&&<section id="k-definition" className="space-y-2"><h4 className="text-sm font-semibold opacity-65">准确表述</h4><FormulaBlock value={knowledge.definitionFormula} label="定义公式"/></section>}
   {knowledge.mechanism&&<section id="k-mechanism" className="space-y-2"><h4 className="text-sm font-semibold opacity-65">机制 / 推理</h4><div className="text-base/8"><RenderRich value={knowledge.mechanism}/></div></section>}
   {!!knowledge.keyPoints?.length&&<ListBlock id="k-key-points" title="关键点" items={knowledge.keyPoints} tone="note"/>}
   {(knowledge.sections||[]).map((section,index)=><section key={section.id||index} id={`k-section-${index}`} className="space-y-2"><h4 className="font-semibold">{section.title||`展开 ${index+1}`}</h4><div className="text-base/8"><RenderRich value={section.body??section.text}/></div>{section.bullets?.length&&<ListBlock title="要点" items={section.bullets}/>} {section.formula&&<FormulaBlock value={section.formula} label={`${section.title||"本节"}公式`}/>} {!!section.formulas?.length&&section.formulas.map((formula,formulaIndex)=><FormulaBlock key={formula.id||formulaIndex} value={formula} label={`${section.title||"本节"}公式 ${formulaIndex+1}`}/>)}{section.note&&<p className="text-sm opacity-70"><RenderRich value={section.note}/></p>}</section>)}
   {!!knowledge.semanticBlocks?.length&&<section id="k-semantic" className="space-y-4">{knowledge.semanticBlocks.map((block,index)=><SemanticBlock key={block.id||index} block={block} index={index}/>)}</section>}
   {!!standaloneFigures.length&&<section id="k-figures" className="space-y-4"><h4 className="text-sm font-semibold opacity-65">教学图</h4>{standaloneFigures.map((figure,index)=><PedagogicalFigure key={figure.id||index} figure={figure}/>)}</section>}
   {(examples.length||knowledge.evidence)&&<section id="k-examples" className="space-y-4"><h4 className="text-sm font-semibold opacity-65">例题 / 证据</h4>{examples.map((example,index)=><WorkedExample key={example?.id||index} example={example} index={index} figure={figureById[example?.figureRef]}/>)}{knowledge.evidence&&<div className="text-base/8"><RenderRich value={knowledge.evidence}/></div>}</section>}
   <ComparisonBlock comparison={knowledge.comparison}/>
   <ListBlock id="k-pitfalls" title="边界与误区" items={[...(knowledge.boundaries||[]),...(knowledge.pitfalls||[])]} tone="warning"/>
   <ListBlock id="k-connections" title="前后连接" items={knowledge.connections} tone="note"/>
   {!!knowledge.glossary?.length&&<section id="k-glossary" className="ic-glossary"><h4 className="text-sm font-semibold opacity-65">术语</h4>{knowledge.glossary.map((item,index)=><p key={item.term||index}><strong>{item.term||"术语"}</strong>{item.definition?<>：<RenderRich value={item.definition}/></>:null}</p>)}</section>}
   <ListBlock id="k-check" title="自检" items={knowledge.checkYourself} tone="note"/>
   {knowledge.takeaway&&<div className="ic-knowledge-takeaway"><span aria-hidden="true">✓</span><span><RenderRich value={knowledge.takeaway}/></span></div>}
  </article>;
 }

function quizTypeWithTypes(item){const type=String(item?.type||"").toLowerCase();if(["multiple","multi","multi-select","checkbox"].includes(type))return "multiple";if(["numeric","number","numerical"].includes(type))return "numeric";if(["ordering","order","排序"].includes(type))return "ordering";return "single";}
function rawQuizAnswerWithTypes(item){return item?.answer??item?.answers??item?.correctAnswer??item?.expected;}
function optionIdWithTypes(option,index){return typeof option==="object"?String(option.id??option.value??index):String(option);}
function optionTextWithTypes(option){return typeof option==="object"?(option.text??option.label??option.value):option;}
function answerArrayWithTypes(value){if(value&&typeof value==="object"&&!Array.isArray(value))return answerArrayWithTypes(value.values??value.ids??value.answer??value.expected);return Array.isArray(value)?value.filter(v=>v!=null).map(String):value==null?[]:[String(value)];}
function defaultQuizAnswerWithTypes(item){const type=quizTypeWithTypes(item);if(type==="ordering")return (item.initialOrder||item.order||(item.options||item.items||[]).map((option,index)=>optionIdWithTypes(option,index))).map(String);if(type==="multiple")return answerArrayWithTypes(item.initialSelection||item.selected||[]);return undefined;}
function selectedQuizAnswerWithTypes(item,answers,key){return answers[key]===undefined?defaultQuizAnswerWithTypes(item):answers[key];}
function sameIdArrayWithTypes(left,right,ordered=false){const a=answerArrayWithTypes(left),b=answerArrayWithTypes(right);if(a.length!==b.length)return false;if(ordered)return a.every((value,index)=>value===b[index]);const sortedA=[...a].sort(),sortedB=[...b].sort();return sortedA.every((value,index)=>value===sortedB[index]);}
function quizItemCorrectWithTypes(item,answers,key=item?.id){const type=quizTypeWithTypes(item);const expected=rawQuizAnswerWithTypes(item);const got=selectedQuizAnswerWithTypes(item,answers,key);if(type==="numeric"){const raw=expected&&typeof expected==="object"&&!Array.isArray(expected)?expected.value??expected.answer??expected.expected:expected;const target=Array.isArray(raw)?raw[0]:raw;const tolerance=Number(item.tolerance??(expected&&typeof expected==="object"&&!Array.isArray(expected)?expected.tolerance:0))||0;const actual=Number(got);return Number.isFinite(actual)&&Number.isFinite(Number(target))&&Math.abs(actual-Number(target))<=Math.max(0,tolerance);}if(type==="ordering")return sameIdArrayWithTypes(got,expected,true);if(type==="multiple")return sameIdArrayWithTypes(got,expected,false);const target=Array.isArray(expected)?expected[0]:expected;return got!=null&&target!=null&&String(got)===String(target);}
function quizFeedbackWithTypes(item,correct){const feedback=item?.feedback;if(typeof feedback==="string")return feedback;return feedback?.[correct?"correct":"incorrect"]||(correct?"回答正确。":"再检查定义、条件或推理。");}

function QuizItemWithTypes({item,index,answers,setAnswers,checked}){
 const key=item.id||String(index),type=quizTypeWithTypes(item),options=item.options||item.items||[],selected=selectedQuizAnswerWithTypes(item,answers,key),order=Array.isArray(selected)?selected:[];
 const moveOrder=(position,direction)=>setAnswers((current)=>{const next=[...(Array.isArray(current[key])?current[key]:order)],target=position+direction;if(target<0||target>=next.length)return current;[next[position],next[target]]=[next[target],next[position]];return {...current,[key]:next};});
 return <fieldset className="rounded-xl border border-black/10 bg-black/[0.025] p-4 dark:border-white/15 dark:bg-white/[0.035]"><legend className="px-1 font-semibold">{index+1}. <RenderRich value={item.prompt}/></legend>{type==="numeric"?<label className="mt-3 block text-sm">输入数值<input className="mt-2 min-h-10 w-full rounded-lg border border-black/15 bg-transparent px-3 dark:border-white/20" type="number" value={selected??""} onChange={(event)=>setAnswers((current)=>({...current,[key]:event.target.value}))}/></label>:type==="ordering"?<ol className="mt-3 space-y-2">{order.map((id,position)=>{const optionIndex=options.findIndex((option,optionPosition)=>optionIdWithTypes(option,optionPosition)===id),option=options[optionIndex];return <li key={`${id}-${position}`} className="flex items-center justify-between gap-3 rounded-lg border border-black/10 p-3 text-sm dark:border-white/15"><span><strong>{position+1}.</strong> <RenderRich value={optionTextWithTypes(option)||id}/></span><span className="flex gap-1"><button type="button" className={buttonClass} aria-label={`上移第 ${position+1} 项`} disabled={position===0} onClick={()=>moveOrder(position,-1)}>↑</button><button type="button" className={buttonClass} aria-label={`下移第 ${position+1} 项`} disabled={position===order.length-1} onClick={()=>moveOrder(position,1)}>↓</button></span></li>;})}</ol>:<div className="mt-3 space-y-2">{options.map((option,optionIndex)=>{const id=optionIdWithTypes(option,optionIndex),checkedValue=type==="multiple"?Array.isArray(selected)&&selected.map(String).includes(id):String(selected??"")===id;return <label key={id} className="flex gap-2 rounded-lg border border-black/10 p-3 text-sm dark:border-white/15"><input type={type==="multiple"?"checkbox":"radio"} name={`q-${key}`} checked={checkedValue} onChange={()=>{if(type==="multiple")setAnswers((current)=>{const values=Array.isArray(current[key])?current[key].map(String):[];return {...current,[key]:values.includes(id)?values.filter((value)=>value!==id):[...values,id]};});else setAnswers((current)=>({...current,[key]:id}));}}/><span><RenderRich value={optionTextWithTypes(option)}/></span></label>;})}</div>}{checked&&<p role="status" className="mt-3 text-sm">{quizItemCorrectWithTypes(item,answers,key)?quizFeedbackWithTypes(item,true):quizFeedbackWithTypes(item,false)}</p>}</fieldset>;
}

function QuizScene({content,mastery=false}){const items=content?.items||content?.questions||[];const [answers,setAnswers]=useState({}),[checked,setChecked]=useState(false);const correct=items.filter((item,index)=>quizItemCorrectWithTypes(item,answers,item.id||String(index))).length;const threshold=content?.masteryGate?.threshold;return <section className="ic-reading space-y-5" data-modern-scene={mastery?"mastery":"quiz"}>{content?.practiceNote&&<p className="text-sm opacity-70">{content.practiceNote}</p>}{items.map((item,index)=><QuizItemWithTypes key={item.id||index} item={item} index={index} answers={answers} setAnswers={setAnswers} checked={checked}/>)}<div className="flex flex-wrap items-center gap-3"><button type="button" className="min-h-11 rounded-lg bg-[var(--ic-accent)] px-4 font-semibold text-white" onClick={()=>setChecked(true)}>检查答案</button>{checked&&<span className="text-sm" aria-live="polite">正确 {correct}/{items.length}{mastery&&threshold!=null?`；总阈值 ${Math.round(Number(threshold)*100)}%`:""}</span>}</div>{mastery&&checked&&<MasterySummary content={content} items={items} answers={answers}/>}</section>;}
function MasterySummary({content,items,answers}){const rules=content?.masteryGate?.objectiveRules||[];const status=rules.map(r=>{const qs=(r.questionIds||[]).map(id=>items.find(x=>x.id===id)).filter(Boolean);const n=qs.filter(q=>quizItemCorrectWithTypes(q,answers,q.id)).length;return {...r,correct:n,pass:n>=Number(r.minCorrect||qs.length)};});return <div className={`${status.every(x=>x.pass)?staticToneClasses.good:staticToneClasses.warning} rounded-xl p-4`}><strong>掌握检查</strong><ul className="mt-2 space-y-1 text-sm">{status.map((r,i)=><li key={r.objectiveId||i}>{r.objectiveId}: {r.correct}/{(r.questionIds||[]).length} {r.pass?"✓":"需要补救"}</li>)}</ul></div>;}


function LegacyApp({course}){
 const reduceMotion=useReducedMotion();const scenes=course.scenes||[],sources=course.sources||[],stages=course.stages||[];const [sceneId,setSceneId]=useState(scenes[0]?.id||null),[query,setQuery]=useState(""),[bookmarks,setBookmarks]=useState([]),[bookmarksOnly,setBookmarksOnly]=useState(false),[bibliographyOpen,setBibliographyOpen]=useState(false),[feedbackOpen,setFeedbackOpen]=useState(false),[feedbackObservations,setFeedbackObservations]=useState([]);const headingRef=useRef(null),mounted=useRef(false);
 useEffect(()=>{if(!scenes.some(s=>s.id===sceneId))setSceneId(scenes[0]?.id||null);},[scenes,sceneId]);
 const sceneIndex=Math.max(0,scenes.findIndex(s=>s.id===sceneId)),scene=scenes[sceneIndex],knowledge=scene?.knowledge||scene?.content?.knowledge,outline=knowledgeOutline(knowledge),title=course?.meta?.title||"互动学习",transition=reduceMotion?{duration:0}:{duration:.18};
 const sceneSearch=useMemo(()=>new Map(scenes.map(s=>[s.id,flattenText({title:s.title,intro:s.intro,knowledge:s.knowledge,content:s.content}) .toLowerCase()])),[scenes]);
 const filteredScenes=scenes.filter(s=>{const q=query.trim().toLowerCase(),matches=!q||sceneSearch.get(s.id)?.includes(q),marked=!bookmarksOnly||bookmarks.includes(s.id);return matches&&marked;});
 const stageGroups=useMemo(()=>{if(!stages.length)return[{id:"all",title:"课程",scenes:filteredScenes}];return stages.map(st=>({id:st.id,title:st.title||st.id,scenes:filteredScenes.filter(s=>s.stageId===st.id)})).filter(g=>g.scenes.length);},[stages,filteredScenes]);
 useEffect(()=>{const live=document.getElementById("live-status");if(live&&scene)live.textContent=`已进入：${scene.title}`;if(mounted.current&&headingRef.current)headingRef.current.scrollIntoView({block:"start",behavior:"auto"});mounted.current=true;},[sceneId,scene]);
 const toggleBookmark=()=>setBookmarks(xs=>xs.includes(sceneId)?xs.filter(x=>x!==sceneId):[...xs,sceneId]);const go=id=>{if(id)setSceneId(id);};const jumpOutline=id=>document.getElementById(id)?.scrollIntoView({block:"start",behavior:"auto"});const progress=scenes.length?Math.round(((sceneIndex+1)/scenes.length)*100):0;const resetLearning=()=>{setBookmarks([]);setBookmarksOnly(false);setQuery("");setFeedbackObservations([]);setSceneId(scenes[0]?.id||null);};
 return <MotionConfig reducedMotion="user"><LazyMotion features={domAnimation} strict><div className="mx-auto min-h-screen w-full max-w-[1560px]"><header className="sticky top-0 z-20 border-b border-black/10 bg-[var(--ic-paper)]/95 px-4 py-3 backdrop-blur dark:border-white/15 sm:px-6"><div className="mx-auto flex max-w-[1480px] flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-[.16em] opacity-55">互动学习</div><h1 className="text-base font-semibold sm:text-lg">{title}</h1></div><div className="flex flex-wrap items-center gap-2 text-sm"><span aria-label={`课程进度 ${progress}%`}>进度 {progress}%</span><button type="button" onClick={toggleBookmark} aria-pressed={bookmarks.includes(sceneId)} className={buttonClass}>{bookmarks.includes(sceneId)?"★ 已收藏":"☆ 收藏本页"}</button><button type="button" onClick={()=>setBookmarksOnly(v=>!v)} aria-pressed={bookmarksOnly} className={buttonClass}>仅看收藏</button><button type="button" onClick={()=>setBibliographyOpen(true)} className={buttonClass}>参考资料</button><button type="button" onClick={()=>setFeedbackOpen(true)} className={buttonClass}>学习反馈</button><button type="button" onClick={resetLearning} className={buttonClass}>重置学习</button></div></div></header>
 <div className="grid grid-cols-1 lg:grid-cols-[250px_minmax(0,1fr)_200px]"><aside className="border-b border-black/10 p-4 dark:border-white/15 lg:sticky lg:top-[73px] lg:h-[calc(100vh-73px)] lg:overflow-auto lg:border-b-0 lg:border-r" aria-label="课程目录"><label className="text-xs font-semibold opacity-60" htmlFor="scene-search">搜索全部课程内容</label><input id="scene-search" value={query} onChange={e=>setQuery(e.target.value)} className="mt-2 min-h-10 w-full rounded-lg border border-black/15 bg-transparent px-3 dark:border-white/20" placeholder="标题、讲解、例题、练习……"/><nav className="mt-4 space-y-4">{stageGroups.map(group=><section key={group.id}><h2 className="px-2 text-xs font-semibold uppercase tracking-[.12em] opacity-50">{group.title}</h2><div className="mt-1 space-y-1">{group.scenes.map(s=><button key={s.id} type="button" onClick={()=>go(s.id)} aria-current={s.id===sceneId?"step":undefined} className="block min-h-11 w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-black/5 aria-[current=step]:bg-black/5 dark:hover:bg-white/5 dark:aria-[current=step]:bg-white/5">{bookmarks.includes(s.id)?"★ ":""}{s.title}</button>)}</div></section>)}{!filteredScenes.length&&<p className="text-sm opacity-60">没有匹配的课程页面。</p>}</nav></aside>
 <main className="min-w-0 px-5 py-8 sm:px-8 lg:px-12">{scene?<m.div key={scene.id} initial={reduceMotion?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transition}><header ref={headingRef} className="ic-reading mb-8 scroll-mt-28"><p className="text-xs font-semibold uppercase tracking-[.14em] opacity-55">{scene.type||"学习"}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-balance">{scene.title}</h2>{scene.intro&&<p className="mt-3 text-base/8 opacity-75">{scene.intro}</p>}</header><SceneBody scene={scene} course={course}/><CitationTrail scene={scene} sources={sources}/><div className="ic-reading mt-10 flex items-center justify-between border-t border-black/10 pt-5 dark:border-white/15"><button type="button" disabled={sceneIndex<=0} onClick={()=>go(scenes[sceneIndex-1]?.id)} className={`${buttonClass} disabled:opacity-35`}>← 上一页</button><span className="text-sm opacity-60">{sceneIndex+1} / {scenes.length}</span><button type="button" disabled={sceneIndex>=scenes.length-1} onClick={()=>go(scenes[sceneIndex+1]?.id)} className={`${buttonClass} disabled:opacity-35`}>下一页 →</button></div></m.div>:<p>课程尚未生成场景。</p>}</main>
 <aside className="hidden border-l border-black/10 p-4 dark:border-white/15 lg:sticky lg:top-[73px] lg:block lg:h-[calc(100vh-73px)] lg:overflow-auto" aria-label="当前页知识目录" data-modern-toc><div className="text-xs font-semibold uppercase tracking-[.14em] opacity-55">本页目录</div><nav className="mt-3 space-y-1">{outline.map(x=><button key={x.id} type="button" onClick={()=>jumpOutline(x.id)} className="block w-full rounded-md px-2 py-1.5 text-left text-sm opacity-75 hover:bg-black/5 hover:opacity-100 dark:hover:bg-white/5">{x.label}</button>)}</nav></aside></div>
 <footer className="border-t border-black/10 px-5 py-5 text-center text-xs opacity-60 dark:border-white/15">离线学习：本页面默认不连接外部模型、分析服务或远程运行时。</footer>
 {bibliographyOpen&&<Modal title="参考资料" onClose={()=>setBibliographyOpen(false)}><ol className="mt-5 space-y-4">{sources.length?sources.map((s,i)=><li key={s.id||i}><strong>[{i+1}] {s.title||s.id}</strong><p className="mt-1 text-sm opacity-75">{[s.author,s.publisher,s.year,s.locator].filter(Boolean).join(" · ")}</p></li>):<li>本课程未声明外部参考资料。</li>}</ol></Modal>}
{feedbackOpen&&<FeedbackDialog course={course} scene={scene} observations={feedbackObservations} setObservations={setFeedbackObservations} onClose={()=>setFeedbackOpen(false)}/>}</div></LazyMotion></MotionConfig>;
}

export default function App({course}) {
 const reduceMotion=useReducedMotion();
 const scenes=Array.isArray(course?.scenes)?course.scenes:[];
 const sources=Array.isArray(course?.sources)?course.sources:[];
 const stages=Array.isArray(course?.stages)?course.stages:[];
 const [sceneId,setSceneId]=useState(scenes[0]?.id||null);
 const [query,setQuery]=useState("");
 const [bookmarks,setBookmarks]=useState([]);
 const [bookmarksOnly,setBookmarksOnly]=useState(false);
 const [bibliographyOpen,setBibliographyOpen]=useState(false);
 const [feedbackOpen,setFeedbackOpen]=useState(false);
 const [feedbackObservations,setFeedbackObservations]=useState([]);
 const headingRef=useRef(null),mounted=useRef(false);
 useEffect(()=>{if(!scenes.some(s=>s.id===sceneId))setSceneId(scenes[0]?.id||null);},[scenes,sceneId]);
 const sceneIndex=Math.max(0,scenes.findIndex(s=>s.id===sceneId));
 const scene=scenes[sceneIndex];
 const knowledge=scene?.knowledge||scene?.content?.knowledge;
 const outline=knowledgeOutline(knowledge);
 const title=course?.meta?.title||"互动学习";
 const transition=reduceMotion?{duration:0}:{duration:.18};
 const sceneSearch=useMemo(()=>new Map(scenes.map(s=>[s.id,flattenText({title:s.title,intro:s.intro,knowledge:s.knowledge,content:s.content}).toLowerCase()])),[scenes]);
 const filteredScenes=scenes.filter(s=>{const q=query.trim().toLowerCase();const matches=!q||sceneSearch.get(s.id)?.includes(q);const marked=!bookmarksOnly||bookmarks.includes(s.id);return matches&&marked;});
 const stageGroups=useMemo(()=>{if(!stages.length)return[{id:"all",title:"课程",scenes:filteredScenes}];return stages.map(st=>({id:st.id,title:st.title||st.id,scenes:filteredScenes.filter(s=>s.stageId===st.id)})).filter(group=>group.scenes.length);},[stages,filteredScenes]);
 useEffect(()=>{const live=document.getElementById("live-status");if(live&&scene)live.textContent=`已进入：${scene.title}`;if(mounted.current&&headingRef.current)headingRef.current.scrollIntoView({block:"start",behavior:"auto"});mounted.current=true;},[sceneId,scene]);
 const selectScene=id=>{if(id)setSceneId(id);};
 const toggleBookmark=()=>setBookmarks(xs=>xs.includes(sceneId)?xs.filter(x=>x!==sceneId):[...xs,sceneId]);
 const jumpOutline=id=>document.getElementById(id)?.scrollIntoView({block:"start",behavior:"auto"});
 const progress=scenes.length?Math.round(((sceneIndex+1)/scenes.length)*100):0;
 const resetLearning=()=>{setBookmarks([]);setBookmarksOnly(false);setQuery("");setFeedbackObservations([]);setSceneId(scenes[0]?.id||null);};
 return <MotionConfig reducedMotion="user"><LazyMotion features={domAnimation} strict><div className="ic-app">
  <header className="ic-topbar"><div className="ic-topbar__inner"><div className="ic-brand"><div className="ic-kicker">互动学习 · 离线工作台</div><h1 className="ic-brand__title">{title}</h1></div><div className="ic-topbar__actions"><span className="ic-progress" aria-label={`课程进度 ${progress}%`}><span>进度 {progress}%</span><span className="ic-progress__track" aria-hidden="true"><span className="ic-progress__fill" style={{width:`${progress}%`}}/></span></span><button type="button" onClick={toggleBookmark} aria-pressed={bookmarks.includes(sceneId)} className={buttonClass}>{bookmarks.includes(sceneId)?"★ 已收藏":"☆ 收藏本页"}</button><button type="button" onClick={()=>setBookmarksOnly(v=>!v)} aria-pressed={bookmarksOnly} className={buttonClass}>仅看收藏</button><button type="button" onClick={()=>setBibliographyOpen(true)} className={buttonClass}>参考资料</button><button type="button" onClick={()=>setFeedbackOpen(true)} className={buttonClass}>学习反馈</button><button type="button" onClick={resetLearning} className={buttonClass}>重置学习</button></div></div></header>
  <div className="ic-workbench"><aside className="ic-scene-rail" aria-label="课程目录"><div className="ic-rail-header"><div><div className="ic-rail-kicker">Course map</div><h2 className="ic-rail-title">课程导航</h2></div><span className="ic-rail-count">{sceneIndex+1}/{scenes.length||0}</span></div><label className="sr-only" htmlFor="scene-search">搜索全部课程内容</label><input id="scene-search" value={query} onChange={e=>setQuery(e.target.value)} className="ic-search" placeholder="搜索标题、讲解、例题……"/><div className="ic-rail-tools"><button type="button" onClick={()=>setBookmarksOnly(v=>!v)} aria-pressed={bookmarksOnly} className={`${buttonClass} text-xs`}>{bookmarksOnly?"显示全部页面":"只看收藏"}</button></div><nav className="ic-scene-list">{stageGroups.map(group=><section key={group.id} className="ic-scene-group"><h3 className="ic-stage-title">{group.title}</h3>{group.scenes.map(s=>{const number=String(scenes.findIndex(item=>item.id===s.id)+1).padStart(2,"0");return <button key={s.id} type="button" onClick={()=>selectScene(s.id)} aria-current={s.id===sceneId?"step":undefined} className="ic-scene-button"><span className="ic-scene-number">{number}</span><span className="ic-scene-button__text">{bookmarks.includes(s.id)?"★ ":""}{s.title}</span></button>;})}</section>)}{!filteredScenes.length&&<p className="text-sm opacity-60">没有匹配的课程页面。</p>}</nav></aside>
   <main className="ic-reading-column">{scene?<m.div key={scene.id} initial={reduceMotion?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transition}><header ref={headingRef} className="ic-lesson-header"><div className="ic-scene-kicker">{scene.type||"学习场景"}</div><div className="ic-lesson-title-row"><h2 className="ic-lesson-title">{scene.title}</h2><span className="ic-scene-index">{sceneIndex+1} / {scenes.length}</span></div>{scene.intro&&<p className="ic-lesson-intro">{scene.intro}</p>}<div className="ic-lesson-actions"><button type="button" onClick={toggleBookmark} aria-pressed={bookmarks.includes(sceneId)} className={buttonClass}>{bookmarks.includes(sceneId)?"★ 已收藏":"☆ 收藏本页"}</button><span className="ic-rail-count">本页内容可离线阅读与操作</span></div></header><div className="ic-scene-body"><SceneBody scene={scene} course={course}/></div><CitationTrail scene={scene} sources={sources}/><nav className="ic-pagination ic-reading" aria-label="场景翻页"><button type="button" disabled={sceneIndex<=0} onClick={()=>selectScene(scenes[sceneIndex-1]?.id)} className={`${buttonClass} disabled:opacity-35`}>← 上一页</button><span className="ic-rail-count">{sceneIndex+1} / {scenes.length}</span><button type="button" disabled={sceneIndex>=scenes.length-1} onClick={()=>selectScene(scenes[sceneIndex+1]?.id)} className={`${buttonClass} disabled:opacity-35`}>下一页 →</button></nav></m.div>:<p>课程尚未生成场景。</p>}</main>
   <aside className="ic-outline-rail" aria-label="当前页知识目录" data-modern-toc><div className="ic-rail-kicker">On this page</div><h2 className="ic-rail-title">本页目录</h2><nav className="ic-outline-list">{outline.map(item=><button key={item.id} type="button" onClick={()=>jumpOutline(item.id)} className="ic-outline-button" >{item.label}</button>)}</nav></aside>
  </div><footer className="ic-footer">离线学习：本页面默认不连接外部模型、分析服务或远程运行时。</footer>
  {bibliographyOpen&&<Modal title="参考资料" onClose={()=>setBibliographyOpen(false)}><ol className="mt-5 space-y-4">{sources.length?sources.map((s,i)=><li key={s.id||i}><strong>[{i+1}] {s.title||s.id}</strong><p className="mt-1 text-sm opacity-75">{[s.author,s.publisher,s.year,s.locator].filter(Boolean).join(" · ")}</p></li>):<li>本课程未声明外部参考资料。</li>}</ol></Modal>}
  {feedbackOpen&&<FeedbackDialog course={course} scene={scene} observations={feedbackObservations} setObservations={setFeedbackObservations} onClose={()=>setFeedbackOpen(false)}/>}</div></LazyMotion></MotionConfig>;
}
